.github/workflows/CI.yml, action.yml
I found a bug. Only the artifacts dir was cached even when more paths were passed in. So, I expanded the tests and confirmed that the test failed. The problem was caused by GitHub dropping newlines somewhere between setting the variable in the first step and reading the variable in the second step.
This is now solved by passing separate variables and joining them (`format`) in the cache step.
=> Also test packages dir

action.yml
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ & https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
=> Remove deprecated set-output command

README.md, action.yml
Closes https://github.com/julia-actions/cache/issues/7
`julia-buildpkg` and `julia-runtest` now both use the pkgserver registry, so this should work
https://github.com/julia-actions/julia-buildpkg/pull/31 - landed properly on https://github.com/julia-actions/julia-buildpkg/releases/tag/v1.4.2
https://github.com/julia-actions/julia-runtest/pull/74 - landed properly on https://github.com/julia-actions/julia-runtest/releases/tag/v1.9.1
=> enable registries by default

.github/workflows/CI.yml, README.md, action.yml, handle_caches.jl
Changes how the default cache key is generated such that YAML objects in the matrix are expanded upon and not just returned as "Object". Due to use combining so many values from the matrix I've also decided to include the key name in the cache key.
The change here should be non-breaking but will result in cache misses when users first update to this version.
Fixes #87.
=> Unique cache-key for job matrix objects

.github/workflows/CI.yml, action.yml
Noticed in a private workflow that when a matrix values contain commas the cache restore step fails with:
```
Error: Key Validation Error: <redacted-key> cannot contain commas.
```
I ended up [tracking down where the key restrictions are implemented](https://github.com/actions/toolkit/blob/5430c5d84832076372990c7c27f900878ff66dc9/packages/cache/src/cache.ts#L32-L44) and found that there are only two restrictions:
- Limited to a length of 512 characters
- Cannot use commas
I've opted to URL encode the comma character only to keep the artifact key as human-readable as possible while still indicating the presence of a comma. I'm not as worried about the key length limit as my artifact key was only 286 characters and was using a pretty complicated job matrix with included paths.
=> URL encode any invalid key characters

.github/workflows/CI.yml, action.yml, handle_caches.jl
I've noticed that the post-action step which automatically cleans up old cache entries accidentally cleans up entries created on other branches. This reduces performance with multiple PRs are being developed concurrently especially in the scenario where a PR deletes the cache entry for the main branch resulting in all new PRs having cache misses until a PR has been merged.
This PR updates the handle_caches.jl script to only delete caches which match the restore key using the same git ref as the executing workflow. This should result in workflows run on the main branch only deleting cache entries on main and PRs only deleting cache entries for that PR.
For more details about cache isolation in regards to branches see: https://docs.github.com/en/actions/using-workflows/caching-dependencies-t …
=> Delete cache entries only on the workflow branch

.github/workflows/CI.yml, action.yml
Avoid restoring cached registries when the user already has registries in the Julia depot. If we restore the cached registries for cloned repos we end up putting the registry worktree into a dirty state which will cause failures when attempting to update the registry later.
Fixes #94.
=> Avoid corrupting existing cloned Julia registries

.github/workflows/CI.yml, action.yml
Some CI refactoring after the work in #102 where I found it easier to pass the unique cache name between save and restore instead of reproducing it.
=> Pass cache-name between save/restore jobs

action.yml
This helps other following actions know that this action ran
i.e. https://github.com/julia-actions/julia-buildpkg/pull/41
Alternatively we could set an env var, but this seems logical to me
=> make depot if not restored

README.md, action.yml
Fixes: https://github.com/julia-actions/cache/issues/104
I took the simplest approach, of just removing the check on whether the runner is hosted by GitHub.  This seems to work for both [non-container](https://github.com/musoke/UltraDark.jl/actions/runs/7547005193/job/20546021767#step:4:1) and [container](https://github.com/musoke/WolframExpr.jl/actions/runs/7546831404/job/20545463332#step:6:34) jobs.
There may be other cases and subtleties that I am missing.
The one caveat is that the container has to have curl installed; this was easy to do but may be worth adding to the readme.
=> fix: Attempt to install jq on all runners

action.yml
Third party actions should never not be pinned to a hash. Otherwise, in case the action repo is taken over by a malicious actor, they can change what runs in all of the workflows that julia-actions/cache is used in as well. Pinning to a hash prevents that.
=> Pin third party action to hash

README.md
The new permissions
```yml
permissions:
actions: write
contents: read
```
can be a bit of a hassle to setup for many repositories.
It's probably good to clarify why these permissions are useful in order to avoid confusion and possibly frustration.
=> Mention why the extra permissions are required

README.md
The README currently provides inaccurate information about GitHub cache retention policy.
=> More accurate info about GitHub cache retion policy

action.yml
Ideally we can merge this as a patch release before https://github.com/julia-actions/cache/pull/120
Fixes #119 
As pointed out in https://github.com/julia-actions/cache/issues/119 this was erroneously left in #71 on a commit that had dependencies updated that didn't correspond with a `actions/cache` release.
=> Update actions/cache to v3.3.3

README.md
The old text contained a typo it seems because it said: "if you do not use a matrix for concurrency you could make `cache-name` such that it is unique".
=> Fix typo in `cache-name` note

README.md
Bash might not be available by default in e.g. self-hosted Windows runners. So we should document this requirement.
=> README: document that Bash is required

action.yml, handle_caches.jl
Fixes https://github.com/julia-actions/cache/issues/113
In https://github.com/julia-actions/cache/pull/71 when we introduced saving cache entries for each matrix job we also introduced a manual cache eviction step to attempt to evict unnecessary cache entries in a better way than the default GitHub behavior (evict the oldest). Unfortunately, we have ended up being a little overly aggressive in our cache eviction policy which has resulted in the following problems:
1. We assume that a cache entry will be saved upon every job run so it is safe to evict all cache entries on that branch before we save the new entry. For failed jobs no new cache entry is saved so we end up starting from scratch on subsequent runs. In this PR I've updated the behavior to always keep the latest cache entry …
=> Fix issues with custom cache eviction

action.yml
I noticed a bug with https://github.com/julia-actions/cache/pull/140 where the registry failed to be updated:
```
...
626M    /home/runner/.julia/registries
20K     /home/runner/.julia/scratchspaces
1.1G    total
Run if [ -d "~/.julia/registries" ] && [ -n "$(ls -A "~/.julia/registries")" ]; then
Registries directory does not exist or is empty. Skipping registry update
```
The problem turned out to be that using `~` in a quoted path doesn't expand it which results in failed checks:
```sh
❯ [ -d "~/.julia/registries" ] && [ -n "$(ls -A "~/.julia/registries")" ] && echo pass
❯ [ -d "$HOME/.julia/registries" ] && [ -n "$(ls -A "$HOME/.julia/registries")" ] && echo pass
pass
```
Seems best we just use the expanded path to avoid these kind of mistakes from occurring again.
=> Expand paths which use tilde

action.yml
Fixes #145 
I guess the bug came from https://github.com/julia-actions/cache/pull/141 but I'm not sure the situation was better before that.
I'll test externally to check.
=> fix windows depot path expansion

README.md
Not necessary for this example. The default works.
=> Fix retry on failure/cancelled example
